# Generated by Django 3.2.6 on 2021-08-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('emailAdresse', models.CharField(help_text='Email', max_length=200)),
                ('subject', models.CharField(help_text='sujet', max_length=200)),
                ('message', models.TextField(help_text='message')),
            ],
        ),
    ]
