# Generated by Django 3.2.6 on 2021-09-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panturaapp', '0002_auto_20210830_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='emailAdresse',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fullName',
            field=models.CharField(max_length=200, verbose_name='Nom & Prenom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Sujet'),
        ),
    ]
