# Generated by Django 3.2.6 on 2021-09-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panturaapp', '0003_auto_20210902_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeConnecter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=200, verbose_name='Email')),
                ('MotDePasse', models.CharField(max_length=200, verbose_name='Mot de passe')),
            ],
        ),
    ]
